# Generated by Django 3.0.5 on 2022-12-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('locationCover', models.CharField(blank=True, max_length=2555, null=True)),
                ('declared_value_or_sumInsured', models.CharField(blank=True, max_length=255, null=True)),
                ('numberOfOccupation_covered', models.PositiveIntegerField()),
                ('sum_insuredPerOccupanr', models.CharField(blank=True, max_length=255, null=True)),
                ('selectCovers', models.CharField(blank=True, choices=[('THIRD PART LIABILITY', 'Third Part Liability'), ('OWN DAMAGE', 'Own Damage'), ('THEFT', 'Theft'), ('FIRE', 'Fire'), ('OCCUPANT', 'OCCUPANT'), ('TPL+', 'Tpl+')], max_length=255, null=True)),
                ('starting_date', models.DateField(auto_now=True)),
                ('ending_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownertype', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicleClassification', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicle_usage', models.CharField(blank=True, max_length=2555, null=True)),
                ('usage_type', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicleManufacture_year', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicleBrand', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicleModel', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicle_chassisNo', models.CharField(blank=True, max_length=2555, null=True)),
                ('vehicle_seat_capacity', models.CharField(blank=True, max_length=2555, null=True)),
                ('duration', models.CharField(blank=True, max_length=2555, null=True)),
                ('locationCover', models.CharField(blank=True, max_length=2555, null=True)),
                ('declared_value_or_sumInsured', models.CharField(blank=True, max_length=2555, null=True)),
                ('numberOfOccupation_covered', models.PositiveIntegerField()),
                ('selectCovers', models.CharField(blank=True, choices=[('THIRD PART LIABILITY', 'Third Part Liability'), ('OWN DAMAGE', 'Own Damage'), ('THEFT', 'Theft'), ('FIRE', 'Fire'), ('OCCUPANT', 'OCCUPANT'), ('TPL+', 'Tpl+')], max_length=2555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200)),
                ('sum_assurance', models.PositiveIntegerField()),
                ('premium', models.PositiveIntegerField()),
                ('tenure', models.PositiveIntegerField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Category')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleClassification', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_usage', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleManufacture_year', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleBrand', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleModel', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_chassisNo', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_seat_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('ownertype', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.VehicleCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('admin_comment', models.CharField(default='Nothing', max_length=200)),
                ('asked_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('Policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Policy')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
