# Generated by Django 4.1.3 on 2022-12-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='InsurenceCategory',
        ),
    ]
