# Generated by Django 4.1.3 on 2022-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_rename_category_insurencecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecovers',
            name='declared_value_or_sumInsured',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-2-9 Months', '1-2-9 Months'), ('3-9 Months', '1-2-9 Months'), ('6-6 Months', '1-2-9 Months')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='numberOfOccupation_covered',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
