# Generated by Django 4.1.3 on 2022-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_insurancecovers_declared_value_or_suminsured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecovers',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=30, null=True),
        ),
    ]
