# Generated by Django 4.1.3 on 2022-12-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurancecovers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='documents',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insured',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicleidentification',
            name='documents',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-2-9 Months', '1-2-9 Months'), ('3-9 Months', '1-2-9 Months'), ('6-6 Months', '1-2-9 Months')], default='1-2-9 Months', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='selectCovers',
            field=models.CharField(blank=True, choices=[('THIRD PART LIABILITY', 'Third Part Liability'), ('OWN DAMAGE', 'Own Damage'), ('THEFT', 'Theft'), ('FIRE', 'Fire'), ('OCCUPANT', 'OCCUPANT'), ('TPL+', 'Tpl+')], default='THIRD PART LIABILITY', max_length=255, null=True),
        ),
    ]
