# Generated by Django 4.1.3 on 2022-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insured_documents_insured_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleidentification',
            name='cust_id',
            field=models.CharField(default='cust864', max_length=70),
        ),
        migrations.AddField(
            model_name='vehicleidentification',
            name='vihecleImage',
            field=models.ImageField(blank=True, max_length=70, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('promanadee et affairs', 'Promanade et Affairs'), ('promanadee et affairs', 'Promanade et Affairs'), ('promanadee et affairs', 'Promanade et Affairs'), ('promanadee et affairs', 'Promanade et Affairs'), ('promanadee et affairs', 'Promanade et Affairs')], max_length=255, null=True),
        ),
    ]
