# Generated by Django 4.1.3 on 2022-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_vehicleidentification_cust_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleidentification',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='insurancecovers',
            name='cust_id',
            field=models.CharField(default='cust49373', max_length=70),
        ),
    ]
