# Generated by Django 4.1.3 on 2022-12-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_alter_insurancecovers_cust_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insured',
            old_name='usage_type',
            new_name='accidentDeath',
        ),
        migrations.RemoveField(
            model_name='insured',
            name='selectCovers',
        ),
        migrations.RemoveField(
            model_name='vehicleidentification',
            name='ownertype',
        ),
        migrations.RemoveField(
            model_name='vehicleidentification',
            name='vehicleClassification',
        ),
        migrations.AddField(
            model_name='insured',
            name='medicalFess',
            field=models.CharField(blank=True, default='00,000.00', max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='vehicleidentification',
            name='vehiclePlateNo',
            field=models.CharField(blank=True, default='RAF98D', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='cust_id',
            field=models.CharField(default='cust90039', max_length=70),
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-2-9 Months', '1-2-9 Months'), ('1-6 Months', '1-6 Months'), ('1-3 Months', '1-3 Months')], default='1-6 Months', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecovers',
            name='locationCover',
            field=models.CharField(blank=True, default='Rwanda', max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='insured',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('unapproved', 'UNAPPROVED'), ('decline', 'DECLINED')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='vehicleBrand',
            field=models.CharField(blank=True, default='HYUNDAI', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='vehicleManufacture_year',
            field=models.CharField(blank=True, default='2022', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='vehicleModel',
            field=models.CharField(blank=True, default='SONATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='vehicle_chassisNo',
            field=models.CharField(blank=True, default='GJG86FS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='vehicle_seat_capacity',
            field=models.CharField(blank=True, default='5', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleidentification',
            name='vehicle_usage',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.vehiclecategory'),
        ),
    ]
