# Generated by Django 4.1.3 on 2022-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_coveridentification_feedback_primium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primium',
            name='cust_id',
            field=models.CharField(default='cust74148', max_length=70),
        ),
    ]
