# Generated by Django 4.1.3 on 2022-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_alter_primium_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primium',
            name='cust_id',
            field=models.CharField(default='cust97867', max_length=70),
        ),
    ]
