# Generated by Django 4.1.4 on 2022-12-17 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0012_alter_primium_cust_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveridentification",
            name="video",
            field=models.FileField(
                null=True,
                upload_to="videos_uploaded",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "MPG", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust40791", max_length=70),
        ),
    ]
