# Generated by Django 4.1.4 on 2022-12-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0013_coveridentification_video_alter_primium_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicleBrand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicleManufacture_year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicleModel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehiclePlateNo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicle_chassisNo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicle_seat_capacity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust71455", max_length=70),
        ),
    ]
