# Generated by Django 4.1.4 on 2022-12-17 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0014_alter_coveridentification_vehiclebrand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveridentification",
            name="video",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "MPG", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vihecleImage",
            field=models.ImageField(blank=True, max_length=70, upload_to=""),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust68296", max_length=70),
        ),
    ]
