# Generated by Django 4.1.4 on 2022-12-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0015_alter_coveridentification_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coveridentification",
            name="video",
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust55872", max_length=70),
        ),
    ]
