# Generated by Django 4.1.4 on 2022-12-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0016_remove_coveridentification_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveridentification",
            name="sumInsured",
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vihecleImage",
            field=models.ImageField(blank=True, max_length=70, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust84109", max_length=70),
        ),
    ]
