# Generated by Django 4.1.4 on 2022-12-18 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0017_alter_coveridentification_suminsured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveridentification",
            name="video",
            field=models.FileField(
                null=True,
                upload_to="videos_uploaded",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "MPG", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="sumInsured",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicleBrand",
            field=models.CharField(
                blank=True, default="HYUNDAI", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicleManufacture_year",
            field=models.CharField(
                blank=True, default="2022", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicleModel",
            field=models.CharField(
                blank=True, default="SONATA", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehiclePlateNo",
            field=models.CharField(
                blank=True, default="RAF98D", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicle_chassisNo",
            field=models.CharField(
                blank=True, default="GJG86FS", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vehicle_seat_capacity",
            field=models.CharField(blank=True, default="5", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="vihecleImage",
            field=models.ImageField(
                blank=True, default=1, max_length=70, upload_to="media/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust97864", max_length=70),
        ),
    ]
