# Generated by Django 4.1.4 on 2022-12-18 00:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_alter_personalprofile_identificationid"),
        ("insurance", "0018_coveridentification_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveridentification",
            name="vehicleowner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverIdentification",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="documents",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="coveridentification",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos_uploaded",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "MPG", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust34904", max_length=70),
        ),
    ]
