# Generated by Django 4.1.4 on 2022-12-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0019_coveridentification_vehicleowner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primium",
            name="accidentDeath",
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name="primium",
            name="medicalFess",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust71189", max_length=70),
        ),
    ]
