# Generated by Django 4.1.4 on 2022-12-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0020_primium_accidentdeath_primium_medicalfess_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primium",
            name="accidentDeath",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust73671", max_length=70),
        ),
    ]
