# Generated by Django 4.1.4 on 2022-12-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0021_alter_primium_accidentdeath_alter_primium_cust_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="primium",
            name="motoGuarantyFound",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AddField(
            model_name="primium",
            name="totalNatePremium",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AddField(
            model_name="primium",
            name="totalPremiumPayable",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AddField(
            model_name="primium",
            name="vat",
            field=models.CharField(
                blank=True, default="00,000.00", max_length=2555, null=True
            ),
        ),
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust19128", max_length=70),
        ),
    ]
