# Generated by Django 4.1.4 on 2022-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insurance",
            "0022_primium_motoguarantyfound_primium_totalnatepremium_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="primium",
            name="cust_id",
            field=models.CharField(default="cust93432", max_length=70),
        ),
    ]
