# Generated by Django 4.1.3 on 2022-12-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_personalprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='country',
            field=models.CharField(blank=True, default='Rwanda', max_length=255, null=True),
        ),
    ]
