# Generated by Django 4.1.3 on 2022-12-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_professiondetails_professionsuboccupation_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='education',
            new_name='Education_Description',
        ),
    ]
