# Generated by Django 4.1.3 on 2022-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_education_education_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Mister', 'Mister'), ('Mrs', 'Mrs'), ('Miss/Mrs', 'Miss/Mrs'), ('Company', 'Company'), ('Joint/Group Acc', 'Joint/Group Acc')], max_length=255),
        ),
    ]
