# Generated by Django 4.1.3 on 2022-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customer_user_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='identificationId',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
