# Generated by Django 4.1.4 on 2022-12-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_country_district_province_sector_village_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupationSub",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Occupation_Description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="occupation",
            old_name="ProfessionsubOccupation_Description",
            new_name="Occupation_Description",
        ),
        migrations.RenameField(
            model_name="personalprofile",
            old_name="civil_status",
            new_name="MaritalStatus",
        ),
        migrations.RenameField(
            model_name="personalprofile",
            old_name="identification",
            new_name="id_type",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="identificationId",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="Country",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="district",
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="ContactPerson",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="NextofKin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="NextofKinContacts",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="PostalAddress",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="SubSectors",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="activitySector",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="classification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="comopanyName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="firstName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="fullName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="idNumber",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="id_picture",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="initials",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MISS", "Miss"),
                    ("MR", "Mister"),
                    ("MRS", "Mrs"),
                    ("MS", "Miss/Mrs"),
                    ("CORP", "Company"),
                    ("J", "Joint/Group Acc"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="lastName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="middleName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="nationality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="physicalAddres",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="placeOfBirth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="postaddres",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="postcode",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="tinDocument",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="ton",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RenameModel(
            old_name="ProfessionsubOccupation_Description",
            new_name="Occupation",
        ),
        migrations.DeleteModel(
            name="Profession",
        ),
        migrations.AddField(
            model_name="occupationsub",
            name="subOccupation_Description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customer.occupation",
            ),
        ),
    ]
